project_id = "zytxwdgzjqrcmbnpgofj"

[functions.webhook-asaas]
verify_jwt = false

[functions.calcular-comissoes]
verify_jwt = false

[functions.processar-pagamento-comissoes]
verify_jwt = false

[functions.verificar-bonus-ltv]
verify_jwt = false

[functions.aprovar-comissoes]
verify_jwt = false
